language: node_js
dist: trusty
sudo: true
node_js:
  - '8'
  - '9'
  - '10'

addons:
  firefox: latest

install:
  - npm install

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm run-script build

#after_script:
#  - npm run coveralls

email:
  on_failure: change
  on_success: never

deploy:
  provider: releases
  api_key:
    secure: q6pLvIM8REEcfP/jxr9roQatJ4PwIsu2tI3AN8VnOmtvpfe9A1syggJIhhPpN3cPMW/kt+X38uQM4vyOM738Iw64vKxVBet3D5CtpUJTXbj90JZApR24Jndet2Hg4nj2sKpVvVRBRxGKZts6IdFiaYq/kYNbYVlCtspfLmVss+1xUN54oUJWQNoeSWX/dPnniKiFsr5j8ejwrv3JI4U1HzLbuF+EfQi93nQuSAvsrsvzdPAwMpOX3F0ADI9sUkNyOLw7OnLPaOYSOmf1zmI1nntQaJbh0Sug5CWlHPMDYZwYl/iebs0XDWKk9iXB3qa7DfAS9j8hAH+kAsqrrXSfsay8yY3Yw8q8oCZm45awiXGe8iTwXBNw5Nt3n8iz/rV72OJRccIrZskhX9HvCk+rXRf1WtdpmFr5cXkDLm4ZmdubRNHeuI6Vr/u/Zqqo7gJUYgSs4wtOKaMS8ydFk9T/3pj4T0N5Bi+mzKRk4tu/SIMjtbnbeIa/ya+/F1HRH0T9nRscrwELo9SeYY+4LhcYJybBFcoj8kXftFdv1UbfXeEUTb6Zm/qoS+0uVoogH/bml5oOVBNnYkD4lGU+btHlbez2M0Xz3BciQ3a8bjNrFq58U1TFfWurRptg5n5041cmQS+ifjGwCOutBzGolUSIl67SKKK2968MehketNE96Yo=
  file:
    - dist/pdf-annotate.js
    - dist/pdf-annotate.js.map
    - dist/pdf-annotate.min.js
    - dist/pdf-annotate.min.js.map
  on:
    tags: true
    node: '8'
    repo: Submitty/pdf-annotate.js
